function Out = Comparator_Tree( input )
    Out = Comparator_D( ...
        Comparator_D( Comparator_D(input(1,:),input(2,:)), Comparator_D(input(3,:),input(4,:)) ), ...
        Comparator_D(input(5,:),input(6,:)) ...
    );
end

